# Generated by Django 4.2 on 2024-08-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254, unique=True, verbose_name='Почта'
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='Пароль'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'subject',
                    models.CharField(max_length=256, verbose_name='Тема'),
                ),
                (
                    'send_date',
                    models.DateTimeField(verbose_name='Дата отправки'),
                ),
                (
                    'receive_date',
                    models.DateTimeField(verbose_name='Дата получения'),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'attachments',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='attachments',
                        verbose_name='Прикрепленные файлы',
                    ),
                ),
                (
                    'email_account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='emails.emailaccount',
                    ),
                ),
            ],
        ),
    ]
