# Generated by Django 4.2 on 2024-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_emailmessage_attachments_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(
                choices=[
                    ('gmail.com', 'Gmail'),
                    ('yandex.ro', 'Yandex'),
                    ('mail.ru', 'Mail.ru'),
                ],
                default=1,
                verbose_name='Провайдер',
            ),
            preserve_default=False,
        ),
    ]
