# Generated by Django 4.2 on 2024-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailaccount_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(
                default=1,
                max_length=128,
                unique=True,
                verbose_name='MessageID',
            ),
            preserve_default=False,
        ),
    ]
