# Generated by Django 4.2 on 2024-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='receive_date',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата получения'
            ),
        ),
    ]
