# Generated by Django 4.2 on 2024-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_emailmessage_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(
                choices=[
                    ('gmail.com', 'Gmail'),
                    ('yandex.ru', 'Yandex'),
                    ('mail.ru', 'Mail.ru'),
                ],
                verbose_name='Провайдер',
            ),
        ),
    ]
